# Generated by Django 5.2.12 on 2026-04-03 11:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casequery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Case Query', 'verbose_name_plural': 'Case Queries'},
        ),
        migrations.AlterModelOptions(
            name='lawyerprofile',
            options={'verbose_name': 'Lawyer Profile', 'verbose_name_plural': 'Lawyer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casequery',
            name='ppc_sections',
            field=models.CharField(blank=True, help_text='Sections identified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casequery',
            name='recommended_lawyers',
            field=models.ManyToManyField(blank=True, help_text='Lawyers recommended', to='accounts.lawyerprofile'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='case_specialty',
            field=models.TextField(help_text='e.g., Murder cases, Civil Fraud, Cyber Crime'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval for recommendation'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='languages',
            field=models.CharField(help_text='e.g., Urdu, English, Punjabi', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format: 00000-0000000-0', regex='^\\d{5}-\\d{7}-\\d$')], verbose_name='CNIC Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact number must be in format: 03XXXXXXXXX', regex='^03\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified the lawyer'),
        ),
    ]
