# Generated by Django 5.2.12 on 2026-04-19 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_casequery_options_alter_lawyerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casequery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lawyerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='casequery',
            name='fir_image',
        ),
        migrations.RemoveField(
            model_name='casequery',
            name='ppc_sections',
        ),
        migrations.RemoveField(
            model_name='casequery',
            name='recommended_lawyers',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='online_availability',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='profile_complete',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='casequery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='case_specialty',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='languages',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='years_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format: 00000-0000000-0', regex='^\\d{5}-\\d{7}-\\d$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.chatsession')),
            ],
        ),
    ]
