# Generated by Django 5.2.12 on 2026-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_casequery_options_alter_lawyerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='online_availability',
            field=models.BooleanField(default=True),
        ),
    ]
