# Generated by Django 5.2.12 on 2026-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lawyerprofile_online_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='casequery',
            name='fir_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
